# Site settings
title: Gadgetry
version: "v1.2"
description: "A functional and fictional device."
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
plugins_dir: ./_plugins
destination: docs

# Tachyons Version
tv: "4.7.0"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# Gems
gems:
  - jekyll-seo-tag
  - hash-joiner
  - json
  - open-uri

# 18F's jekyl-get attributes
jekyll_get:
  data: gadgetry
  json: 'https://gist.githubusercontent.com/gwijthoff/00f0f38f2257f8124b34b09ff52e476e/raw/8aeea183f4739f37683ceb46d73aa2361f0c1925/json_test3.json'
  cache: false
