# Site settings
title: Gadgetry
version: "v1.2"
description: "A functional and fictional device."
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
plugins_dir: ./_plugins
destination: docs

# Tachyons Version
tv: "4.7.0"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# Gems
gems:
  - jekyll-seo-tag
  - hash-joiner
  - json
  - open-uri

# 18F's jekyl-get attributes
jekyll_get:
  data: gadgetry
  json: '_data/gadget_data.json'
  cache: false
